= Servo Library for Zumo32U4 =

Enables using the timer4 and digital pin 6 of the Pololu Zumo32u4 robot platform.
This requires you to cut the buzzer jumper to free the timer and pin.

It's needed because the motor controls use timer1 and conflict with the standard Servo library.

== License ==

Copyright (c) 2017 Jimmy Larsson. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
